apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: column-filters-backfill-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: column-filters-backfill
spec:
  containers:
    - name: column-filters-backfill
      image: ubuntu:latest
      command:
        - "/bin/bash"
      args:
        - "-c"
        - "trap : TERM INT; sleep infinity & wait"
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: column-filters-backfill-pvc
